import Config

application_port = String.to_integer(System.get_env("PORT") || "4000")

secret_key_base =
  System.get_env("SECRET_KEY_BASE") || raise("environment variable SECRET_KEY_BASE is missing.")

website_host = System.get_env("WEBSITE_HOST") || "example.com"

config :elixir_logging,
  base_url: "https://#{website_host}",
  scheme: "https",
  website_host: website_host

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :elixir_logging, ElixirLoggingWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: application_port, transport_options: [socket_opts: [:inet6]]],
  live_view: [signing_salt: secret_key_base],
  secret_key_base: secret_key_base,
  server: true,
  url: [host: website_host, port: application_port]
